/*
 * Problem 2: Even Fibonacci numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <iostream>

using namespace std;

int main(void) 
{
	const int max = 4000000;
	int first = 1;
	int second = 2;
	int sum = 0;
	while(second < max)
	{
		if(second % 2 == 0)
		{
			sum += second;
		}
		int temp = first + second;
		first = second;
		second = temp;
	}
	cout << sum << endl;
}